# -*- coding: utf-8 -*-
"""Model_2282455_project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1H6OUPQpJ7mKmcWU1vSEYd5z1YjQX7---
"""

pip install inference_sdk

from inference_sdk import InferenceHTTPClient
import ipywidgets as widgets
from IPython.display import display
import io
from PIL import Image

# initialize the client
CLIENT = InferenceHTTPClient(
    api_url="https://detect.roboflow.com",
    api_key="QcrscXSvqTe51XNx0x6E"
)

# Function to perform inference
def perform_inference(b):
    # Read the uploaded image content
    image_bytes = image_upload.data[-1]

    # Convert the image bytes to PIL Image object
    img = Image.open(io.BytesIO(image_bytes))

    # Perform inference
    result = CLIENT.infer(img, model_id="flower-identification-bqpla/2")
    print(result['predicted_classes'])  # Modify this to display the result as per your requirement

# Create a file upload widget
image_upload = widgets.FileUpload(
    accept='image/*',  # Accept any file type
    multiple=False  # Allow only single file upload
)

# Create a button to trigger inference
infer_button = widgets.Button(description="Infer")
infer_button.on_click(perform_inference)

# Display the widgets
display(image_upload)
display(infer_button)

